### ISSUE TITLE
[Bug]: Remere's map editor bugs

### ISSUE THREAD

**Issue by joelslamospersson** [opentibiabr/remeres-map-editor#10]
### What happened?

Map editor, can't see 469 (Stair)
toolbrush does not work for stone floor (id:499)
RME, Piñata Dragon is bugged (Monster, can't be selected)
Signs seems to be bugged
Blackboards are bugged, all writable? -- Not possible to write anything.

### How to Reproduce?

No positions

### Version

12.x (Default)

### What OS are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MajestyOTBR** [comment]
`Map editor, can't see 469 (Stair)` - Fixed: https://github.com/opentibiabr/remeres-map-editor/pull/11
`toolbrush does not work for stone floor (id:499)` - Tested and worked. 
`RME, Piñata Dragon is bugged (Monster, can't be selected)` - data/creatures/monsters.xml, fix to `<monster name="Pinata Dragon" looktype="0" />`
`Signs seems to be bugged` - ids `2012-2017`, `2023-2024` fix with tag `<attribute key="allowdistread" value="1"/>`
`Blackboards are bugged, all writable? -- Not possible to write anything.` - 2598 (writeable), 2602 (writeable)
