### ISSUE TITLE
error when pasting a post

### ISSUE THREAD

**Issue by luiscaldera** [opentibiabr/remeres-map-editor#106]
When I copy a coordinate directly into Rm and try to paste it when I use the Ctrl+G function, it does not paste it correctly but instead adds the entire coordinate only in the first box.
Test video
https://gyazo.com/f04763e7dd83951c33f12a6a9a176526
and this is the version of my RME
![image](https://github.com/user-attachments/assets/b02b5beb-860a-401b-9a8b-eb6b08b819a7)

**Comment by majestyotbr** [comment]
This is already fixed.
Download RME again and compile it.
