### ISSUE TITLE
[CRASH] while placing spawns

### ISSUE THREAD

**Issue by Schiffers** [opentibiabr/remeres-map-editor#121]
As the tittle says...

when you use the function to generate the spawns with smaller sizes of spawn works fine
with bigger spawn size crash
![image](https://github.com/user-attachments/assets/f85792b7-d9df-43c8-b94a-b88f9128acb8)
imagem marked only 2 monsters smaller spawn size
![image](https://github.com/user-attachments/assets/c3ceea57-05ce-43d2-b783-94972606c669)
working correctly.

now with bigger spawn

![image](https://github.com/user-attachments/assets/07c03f2c-2b38-4546-a791-69d118d08b75)

crash directly.

**Comment by phacUFPE** [comment]
Could you please try the new feature with mosnters weight? It introduces a new feature but fixes this issue as well.
