### ISSUE TITLE
Problem with import map 12.86

### ISSUE THREAD

**Issue by whitecrixu** [opentibiabr/remeres-map-editor#18]
Hi when i try import my map from 12.85 to 12.86 i see this error

![image](https://user-images.githubusercontent.com/63555106/166492692-84599e65-869a-4589-9d81-da1342e0ed47.png)

and after loading i see problem with map...

![image](https://user-images.githubusercontent.com/63555106/166492764-f55cfe4c-64f0-4073-91ef-08821a9603ec.png)

someone know how solved that ?

**Comment by dudantas** [comment]
Map 12.85 and 12.86 are the same, the difference is just the number, but they are saved under the same flag

**Comment by whitecrixu** [comment]
> Map 12.85 and 12.86 are the same, the difference is just the number, but they are saved under the same flag

ok how you explain this

![image](https://user-images.githubusercontent.com/63555106/166555194-0c980868-9a3f-400c-8675-f389f3e4e79c.png)

![image](https://user-images.githubusercontent.com/63555106/166555533-cb1ee1b5-bd4a-4d16-8a84-97a184c4607b.png)

server canary 1.3.1

**Comment by LeeoMacedo** [comment]
> > Map 12.85 and 12.86 are the same, the difference is just the number, but they are saved under the same flag
> 
> ok how you explain this
> 
> ![image](https://user-images.githubusercontent.com/63555106/166555194-0c980868-9a3f-400c-8675-f389f3e4e79c.png)
> 
> ![image](https://user-images.githubusercontent.com/63555106/166555533-cb1ee1b5-bd4a-4d16-8a84-97a184c4607b.png)
> 
> server canary 1.3.1 Nevermind with version map i use i try 12.85 and 12.86

did you convert your map to clientid?

**Comment by dudantas** [comment]
Don't you think it's best to just grab our most up-to-date map?

**Comment by whitecrixu** [comment]
But I use my project :) is my map

**Comment by whitecrixu** [comment]
> Don't you think it's best to just grab our most up-to-date map?

But I want use my map

**Comment by dudantas** [comment]
Then follow this tutorial: https://majestyotbr.gitbook.io/opentibiabr/others/tutorials/mapping/windows-remeres-map-editor-converting-map-server-id-to-client-id

**Comment by whitecrixu** [comment]
> Then follow this tutorial: https://majestyotbr.gitbook.io/opentibiabr/others/tutorials/mapping/windows-remeres-map-editor-converting-map-server-id-to-client-id

Ok thanks i try tomorrow and write results :)

**Comment by ferobra** [comment]
For me it doesn't work, I used your outdated file, I opened the map and it's what's on the screen below, import the same, on the remeres normal map it opens correctly only that without spawn npc and monsters, copying files and renaming it also does not work because probably in remeres is different structure of it

![Screen Shot 05-30-22 at 11 16 AM](https://user-images.githubusercontent.com/106522487/170960196-30192c11-85d6-4111-af67-6056aadcd805.PNG)
![Screen Shot 05-30-22 at 11 15 AM](https://user-images.githubusercontent.com/106522487/170960226-94e9b9a9-7b35-4234-8c00-e0866f03acee.PNG)
![Screen Shot 05-30-22 at 11 10 AM](https://user-images.githubusercontent.com/106522487/170960241-be113b71-75d8-4715-a8bd-b529eae38a45.PNG)
![Screen Shot 05-30-22 at 11 03 AM](https://user-images.githubusercontent.com/106522487/170960259-531b99c9-9c23-43e4-bff2-f68bf37b2a55.PNG)
![Screen Shot 05-30-22 at 10 28 AM](https://user-images.githubusercontent.com/106522487/170960274-fa957c6d-d80a-4036-983d-d61c48560c87.PNG)

**Comment by whitecrixu** [comment]
> For me it doesn't work, I used your outdated file, I opened the map and it's what's on the screen below, import the same, on the remeres normal map it opens correctly only that without spawn npc and monsters, copying files and renaming it also does not work because probably in remeres is different structure of it
> 
> ![Screen Shot 05-30-22 at 11 16 AM](https://user-images.githubusercontent.com/106522487/170960196-30192c11-85d6-4111-af67-6056aadcd805.PNG)
> ![Screen Shot 05-30-22 at 11 15 AM](https://user-images.githubusercontent.com/106522487/170960226-94e9b9a9-7b35-4234-8c00-e0866f03acee.PNG)
> ![Screen Shot 05-30-22 at 11 10 AM](https://user-images.githubusercontent.com/106522487/170960241-be113b71-75d8-4715-a8bd-b529eae38a45.PNG)
> ![Screen Shot 05-30-22 at 11 03 AM](https://user-images.githubusercontent.com/106522487/170960259-531b99c9-9c23-43e4-bff2-f68bf37b2a55.PNG)
> ![Screen Shot 05-30-22 at 10 28 AM](https://user-images.githubusercontent.com/106522487/170960274-fa957c6d-d80a-4036-983d-d61c48560c87.PNG)
> 

Use this tutorial 

https://majestyotbr.gitbook.io/opentibiabr/others/tutorials/mapping/windows-remeres-map-editor-converting-map-server-id-to-client-id

**Comment by whitecrixu** [comment]
> > For me it doesn't work, I used your outdated file, I opened the map and it's what's on the screen below, import the same, on the remeres normal map it opens correctly only that without spawn npc and monsters, copying files and renaming it also does not work because probably in remeres is different structure of it
> > 
> > ![Screen Shot 05-30-22 at 11 16 AM](https://user-images.githubusercontent.com/106522487/170960196-30192c11-85d6-4111-af67-6056aadcd805.PNG)
> > ![Screen Shot 05-30-22 at 11 15 AM](https://user-images.githubusercontent.com/106522487/170960226-94e9b9a9-7b35-4234-8c00-e0866f03acee.PNG)
> > ![Screen Shot 05-30-22 at 11 10 AM](https://user-images.githubusercontent.com/106522487/170960241-be113b71-75d8-4715-a8bd-b529eae38a45.PNG)
> > ![Screen Shot 05-30-22 at 11 03 AM](https://user-images.githubusercontent.com/106522487/170960259-531b99c9-9c23-43e4-bff2-f68bf37b2a55.PNG)
> > ![Screen Shot 05-30-22 at 10 28 AM](https://user-images.githubusercontent.com/106522487/170960274-fa957c6d-d80a-4036-983d-d61c48560c87.PNG)
> > 
> 
> Use this tutorial 
> 
> https://majestyotbr.gitbook.io/opentibiabr/others/tutorials/mapping/windows-remeres-map-editor-converting-map-server-id-to-client-id

But if you want convert from client id to server id i don't think so is possible.
