### ISSUE TITLE
Problem with compiling on Linux Ubuntu

### ISSUE THREAD

**Issue by whitecrixu** [opentibiabr/remeres-map-editor#43]
Hi i have error when i try compiling RME on Ubuntu 20.04 anybody know reason why?
```
-- Compiler: GCC - Version: 11.4.0
CMake Error at source/CMakeLists.txt:7 (find_package):
  Could not find a package configuration file provided by "asio" with any of
  the following names:

    asioConfig.cmake
    asio-config.cmake

  Add the installation prefix of "asio" to CMAKE_PREFIX_PATH or set
  "asio_DIR" to a directory containing one of the above files.  If "asio"
  provides a separate development package or SDK, be sure it has been
  installed.

```

**Comment by majestyotbr** [comment]
Did you followed the wiki?
<https://github.com/opentibiabr/remeres-map-editor/wiki/Compiling-on-Ubuntu-20.04>

**Comment by dudantas** [comment]
The GitHub actions build is running normally on ubuntu, which indicates that you missed something in your environment, or you are not following the tutorial.
![image](https://github.com/opentibiabr/remeres-map-editor/assets/8551443/d7b5432c-cd22-4525-9886-8a82235d7484)

**Comment by whitecrixu** [comment]
Everything doing step by step so when I use commend 
Cmake .. is say error with asio... So any ide ?
