### ISSUE TITLE
erro na abertura do cmake

### ISSUE THREAD

**Issue by luanluciano93** [opentibiabr/remeres-map-editor#48]
@beats-dh 
![image](https://github.com/opentibiabr/remeres-map-editor/assets/6209529/8415dbcd-ae5e-4034-a194-46b20d37cf56)

**Comment by beats-dh** [comment]
Você esta com a variável de ambiente do VCPKG_ROOT?

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/remeres-map-editor/wiki/Compiling-on-Windows-(CMake)

**Comment by majestyotbr** [comment]
Você está no discord, pode pedir suporte para compilação lá e não em issue.
Leia o tutorial e tente novamente.
