### ISSUE TITLE
rme map editor problem with asio Debian 12

### ISSUE THREAD

**Issue by whitecrixu** [opentibiabr/remeres-map-editor#49]
CMake Error at source/CMakeLists.txt:7 (find_package):
  Could not find a package configuration file provided by "asio" with any of
  the following names:

    asioConfig.cmake
    asio-config.cmake

  Add the installation prefix of "asio" to CMAKE_PREFIX_PATH or set
  "asio_DIR" to a directory containing one of the above files.  If "asio"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/remeres-map-editor/wiki/Compiling-on-Debian
