### ISSUE TITLE
moving or deleting an object alters the surrounding objects.

### ISSUE THREAD

**Issue by odisk777** [opentibiabr/remeres-map-editor#61]
When you move an object or delete an object, the surrounding objects are altered. In the first versions, this conflict of objects did not happen.
![Animation](https://github.com/opentibiabr/remeres-map-editor/assets/65802862/20e90b70-602f-4e2e-91f3-cdd5c13fbd2f)

**Comment by foschetti** [comment]
If you press the letter "A" before moving the object you will deactivate the "borders" brush and the surrounding objects will not move anymore. I don't know if this is really a unwanted 'feature'.

**Comment by majestyotbr** [comment]
Disable autoborder (A).
