### ISSUE TITLE
DAT. SPT.

### ISSUE THREAD

**Issue by Chapeleiiro** [opentibiabr/remeres-map-editor#86]
I am using RME, but DAT and SPR are from client 11 available. When I use Client Convert to convert my assets to DAT and SPR, RME does not recognize them. I tested it with assets from the global test server, and it also does not recognize them, only with the global client. Is there a reason for this?

**Comment by majestyotbr** [comment]
This is not a issue related to the map editor, it is a custom support. Ask for support in the Discord and wait someone answer.
