### ISSUE TITLE
[Bug] Map Loading Error and Performance Issue with High Zoom

### ISSUE THREAD

**Issue by Peeedroferreira** [opentibiabr/remeres-map-editor#88]
I am currently using the ### **PR feat-read-assets-from-client-11+** in my OTServer project and have encountered the following issues:

**1. Performance Issue:**
When zooming in on the map, the editor performance significantly degrades, often resulting in the editor freezing or crashing.

**2. Map Loading Error:**
When attempting to open another map, the following error message appears:

`The loaded map appears to be a OTBM format that is not supported by the editor. Do you still want to attempt to load the map? Caution: this will close your current map!
`

![image](https://github.com/user-attachments/assets/441c6e24-7130-42e3-86e2-8144fb59310e)

**Steps to Reproduce:**

1. Open the map editor.
2. Zoom in significantly on any map.
3. Observe the performance degradation.
4. Try to open another map and observe that the current open map closes and the error message appears.

**Expected Behavior:**

- The map editor should handle high zoom levels without significant performance issues.
- The map editor should allow multiple maps to be open in different tabs without closing the current map.

**Environment:**

- Operating System: Windows 11
- Editor Version: e499ad9 (last week)
- PR Branch: feat-read-assets-from-client-11+

**Additional Context:**
This issue is impacting my ability to efficiently work on maps and manage different map files. Any assistance or fix for these issues would be greatly appreciated.

Thank you for your attention to these matters.

**Comment by majestyotbr** [comment]
You should comment with your tests in the [pull request](https://github.com/opentibiabr/remeres-map-editor/pull/70), not create a issue.
The pull request is not merged yet.
