### ISSUE TITLE
Border placement issue, causing incorrect display in-game

### ISSUE THREAD

**Issue by Mifuno** [opentibiabr/remeres-map-editor#95]
Repored using branch: [feat](feat: read assets from client 11+)https://github.com/opentibiabr/remeres-map-editor/pull/70
Example - Marapur created by map tracking.

When opening the Map using an older version of RME
![image](https://github.com/user-attachments/assets/142e33dd-ef18-4843-87d6-2dd7adfa6c5b)

When oepning the Map using the current version of RME
![image](https://github.com/user-attachments/assets/9b5f88d4-216a-48ab-a850-1eb373da2434)

Using the new RME currently we are unable to place border in orders, the way it use to be

In-game screen
![image](https://github.com/user-attachments/assets/d0f807e2-fafe-4279-b18e-d3ad54908557)

Same thing with map tracked Rotten Blood maps
![image](https://github.com/user-attachments/assets/55f4fefb-c373-43d7-aec9-fb359c981531)

**Comment by majestyotbr** [comment]
You should comment in the pull request, not create an issue.
If you find problems testing it, comment there.
