### ISSUE TITLE
Check properties on border result in a debug error

### ISSUE THREAD

**Issue by Mifuno** [opentibiabr/remeres-map-editor#96]
Branch: https://github.com/opentibiabr/remeres-map-editor/pull/70

Right Click on border item
Select option: Properties

![image](https://github.com/user-attachments/assets/b1ff46ac-ed37-404b-9dee-333ad192dcb4)

**Comment by majestyotbr** [comment]
You should comment in the pull request, not create an issue.
If you find problems testing it, comment there.
